### ISSUE TITLE
Provide Examples

### ISSUE THREAD

**Issue by GlenCFL** [smhxx/atom-ts-transpiler#12]
**Related issues (if any):** none
**Type of issue:** ✨Feature Request
**Urgency:** 📆Whenever

I think there should be a few example projects either nested within a subdirectory of this project or linked within the README. One example should be bare bones, with the other being extensive in regards to the tooling surrounding the entire process, so properly configured with things like TravisCI, Code Climate, Coverage, and so on. The code for each of the packages can be minimal and practically useless, as this isn't what people need help with when adopting TypeScript for Atom package development.

The source files within these directories/repositories should probably be under public domain.

**Comment by smhxx** [comment]
Good idea! I'm about to start working on a package of my own using `atom-ts-transpiler` and `@types/atom`, so hopefully I'll be able to leverage what I learn from that into a suitable example setup. I like the idea of having at least two examples, one bare-bones and the other more "opinionated" in terms of its setup. I definitely think this is worth doing once I actually have a more solid grasp on what makes a good foundation for a TypeScript-based Atom package. 👍

**Comment by smhxx** [comment]
For the time being, I've updated the README to encourage anyone using `atom-ts-transpiler` to submit their project as an example, and hopefully by 1.2.2 I'll have gotten far enough into my own project to convert it into a new project "skeleton" like you mentioned.
