### ISSUE TITLE
Lazily require dependencies

### ISSUE THREAD

**Issue by BinaryMuse** [smhxx/atom-ts-transpiler#2]
Hey there! Thanks for the awesome module! I think this is the first community-created Atom transpiler setup. 🎉 

I was glancing through the code and noticed the various requires at the top of the file. While developing the Atom per-package transpilation feature, I found that there could be pretty severe performance hits when requiring certain things (e.g. requiring `babel` can be heavy). So I recommend moving to use lazy-requires; for example, like this: https://github.com/atom/atom-babel6-transpiler/blob/353032ccdd0dd5606ba15f2eab5f0c971002a3f8/lib/index.js#L45

**Comment by BinaryMuse** [comment]
(To clarify, this is mainly because we call `getCacheKeyData` a lot but not necessarily `transpile` if the package is in Atom's on-disk compile cache, so there's no need to require e.g. `typescript` if everything is cached.)

**Comment by smhxx** [comment]
Ah, I wondered why `atom-babel6-transpiler` did that! I noticed it, but wasn't really sure what the reason was. That makes sense - don't load the transpiler until you *know* you're going to have to use it, because everything needed may be in the cache already. Good insight, I'll go ahead and make that change!

**Comment by smhxx** [comment]
Moved the requires into the `transpile()` method and pushed out a 0.2.1! Thanks for the info on Atom's internals, I don't think I would have figured that out on my own. 😛

Out of curiosity, how did this catch your attention so quickly? You must have eyes everywhere, I think I published it yesterday afternoon or something? haha
